version: "1.0"

# Cache settings: Set to true to enable caching
cache: true

registration:
  socialLogins: ['github', 'google', 'discord', 'openid', 'facebook', 'apple', 'saml']

mcpServers:
  graphdb:
    type: streamable-http
    url: "http://mcp-graphdb:8080/mcp"
    timeout: 300000
    initTimeout: 60000
  qdrant:
    type: streamable-http
    url: "http://mcp-qdrant:8080/mcp"
    timeout: 300000
    initTimeout: 60000

interface:
  customWelcome: "Ask the Knowledge Graph!"
  # MCP Servers UI configuration
  mcpServers:
    placeholder: 'MCP Servers'
  
  endpointsMenu: true
  modelSelect: true
  parameters: true
  sidePanel: true
  presets: true
  prompts: true
  bookmarks: true
  multiConvo: true
  agents: true

# endpoints:
#   openAI:
#     addParams:
#       stream: false
#       parallel_tool_calls: false